### ISSUE TITLE
Mithril is nuking away jQuery calendar

### ISSUE THREAD

**Issue by kvanberendonck** [lhorie/mithril.js#463] opened 2015-02-18 23:24 UTC
jQuery inserts a calendar at the top level of the page (last child of `body` tag) to show and bring to focus above everything else for picking dates. Mithril doesn't know about this calendar. Sometimes when an element is added to the end of the page via mithril, this calendar will get killed and jQuery will go into a buggy state where the popup calendars stop working completely.

I right clicked the calendar, break on -> node removal and it came to this line of code when the bug happened:
https://github.com/lhorie/mithril.js/blob/next/mithril.js#L194

**Comment by kvanberendonck** [comment] 2015-02-19 00:12
Okay, so we found a workaround for this.

To make sure mithril never pushes and pops from the same scope that the calendar is inserted (body) we wrapped the whole page inside a useless div which fixed the bug.

**Comment by mindeavor** [comment] 2015-02-26 03:23
I wouldn't call it bodge-patch. It's expected behavior that Mithril clears out the entire contents of the element you assign it to.

**Comment by kvanberendonck** [comment] 2015-02-26 03:42
The calendar is added in config. It's expected that 3rd party integration will work, especially with jQuery.

**Comment by barneycarroll** [comment] 2015-02-26 03:58
@kvanberendonck can you put up a jsFiddle? The suggested usage of config to house 3rd party DOM plugins is to create a Mithril DOM node specifically for that plugin and use config's `el` argument to manipulate the DOM inside that node. What you're talking about should be trivial using this method. Manipulating that node's  parents or siblings is effectively 3rd party code touching nodes that belong to Mithril, which should be expected to break.

**Comment by kvanberendonck** [comment] 2015-02-26 04:02
Looks like I didn't mention it, but we're using `config` here in combination with `isInitialised` too.

**Comment by kharin** [comment] 2015-03-02 17:18
This is not a bug, even more so if jQ is doing it outside of Mithril's scope. Also, rendering into a container `div` is an established practice be it Mithril or React, since by rendering into `body` you're breaking your user's browser extentions which also tend to append stuff to `body`.

**Comment by kvanberendonck** [comment] 2015-03-02 19:37
The way you just put it, it still sounds like a bug to me.

**Comment by barneycarroll** [comment] 2015-03-03 09:09
But you know how you've broken it and how to fix it, right?

**Comment by kvanberendonck** [comment] 2015-03-03 09:33
I'll be honest, my team would have never figured it out. I literally had to debug the guts of mithril to know what was going on, and I wasted a good day or two doing so.

It's also seemingly random and manifests itself in strange places, sometimes and sometimes not. It's also not documented anywhere.

**Comment by barneycarroll** [comment] 2015-03-03 10:13
You said it yourself: you were using config to manipulate DOM structure
outside the config scope. That's somewhat obviously 'out of scope' by your
own admission. The documentation says "This special parameter allows you to
call methods on the DOM element after it gets created." You say "my team
would have never figured it out", but you did, 45 minutes after your
original post.

Is it a case of the documentation not being clear enough? It might be worth
adding something to the effect of "A `config` function and it's arguments
are specifically associated with the DOM elements they are bound to. If you
want access to DOM elements in an external scope, use those elements'
`config` attributes."

**Comment by kvanberendonck** [comment] 2015-03-03 10:20
You can tailor it like it sounds I was doing something outrageous, but we know that this breaks core functionality of jQuery -- one of the worlds most largely used javascript libraries -- and as already mentioned browser plugins, etc.

**Comment by barneycarroll** [comment] 2015-03-03 10:24
It's not outrageous, it's just misusing the function. When you use it according to the documentation, it works. Or doesn't it?

**Comment by kvanberendonck** [comment] 2015-03-03 10:27
You classify this then as misusing config:
```
var myconfig = function(dom) {
    $(dom).datepicker();
}
```
Or, this also, as it will implicitly insert resize handles one level above the element:
```
var myconfig = function(dom) {
    $(dom).resizeable();
}
```
Yes, that's outrageous and completely intuitive.

**Comment by barneycarroll** [comment] 2015-03-03 12:04
The misuse I was referring to was using `config` to manipulate elements outside of scope. Are you saying you're still suffering from unexpected behaviour when using it as above? [I've knocked up a fiddle to try and find bugs with the plugins you mention](http://jsfiddle.net/barney/8ht9rmw4/) but I couldn't find any. Could you fork it to reproduce them, perhaps?

**Comment by kvanberendonck** [comment] 2015-03-03 12:24
To reproduce it, the app actually has to move quite dynamically and cause mithril to touch a lot of DOM. In an application of several hundred dynamic data entry screens with rows and fields that appear and disappear, it was only reproducible in one or two places.

I made a bogus one with lots of dynamic redraws on it and all types of random broken crap to see if I could reproduce it in a fiddle, but I can't ( http://jsfiddle.net/43r7jtj6/ ).

**Comment by lhorie** [comment] 2015-03-03 14:09
@kvanberendonck I feel like this should be fixable, since Mithril keeps a record of managed DOM elements in the cached tree and it should be able to tell that a DOM element is not managed internally. Were you using `<body>` as a rendering target (i.e. `m.route(document.body, ...`) or generating it with `m("body")`?

**Comment by kvanberendonck** [comment] 2015-03-04 00:16
`m.route(document.body, ...)` is how mithril is configured.

If I undo the patch which fixes the issue and dump out mithrils guts with the debugger maybe it will give an idea of how to build a test case.

**Comment by lhorie** [comment] 2015-03-04 00:26
Ok, thanks. I'll look into it

**Comment by ariutta** [comment] 2015-03-12 19:24
[Here's a simplified example](http://plnkr.co/edit/FzbCFoOaNyAfVPNCqLDk?p=preview) of a similar issue I ran into and how I solved it. Mithril creates a header, body and footer, and another library adds a sub-component to the body. Mithril uses routes to change the header and footer when the user clicks the link in the footer.

Once it's created, the sub-component should not be re-rendered, and any event emitters and listeners need to continue working, even if the route changes. My example works -- the time doesn't change and clicking the input box brings up an alert -- but I don't know whether this is a good way to do this.

**Comment by barneycarroll** [comment] 2015-03-12 20:17
@ariutta that's a really interesting and legitimate case in point — ironically I think the compoments branch would have solved this issue until a recent fix in response to a user complaining that reinstating the same component on route change was unexpected behaviour.

**Comment by lhorie** [comment] 2015-03-14 03:01
minimal reproducible test case: http://jsfiddle.net/yhLwmqfx/

**Comment by lhorie** [comment] 2015-03-14 03:24
Fixed in origin/next. This will be release in v0.1.31 (or 0.2 if there's a version bump)

**Closed by lhorie** 2015-03-14 03:24 UTC

**Comment by kvanberendonck** [comment] 2015-03-14 05:27
Thanks Leo! Nice find!
