### ISSUE TITLE
[rewrite] Make it easier to require streams

### ISSUE THREAD

**Issue by sebastiansandqvist** [lhorie/mithril.js#1239] opened 2016-08-14 21:32 UTC
### Description:

(Feature request)

I enjoy using mithril's streams outside of web app development, and currently in order to just import `m.prop`-like functionality into a project, something like this is required:

```js
const log = console.error.bind(console);
const Stream = require('mithril/util/stream')(log);
const stream = Stream.stream;
stream.combine = Stream.combine;
// ... etc
```

It would be nice to instead be able to do something like this:

```js
const stream = require('mithril/stream');
```

**Comment by lhorie** [comment] 2016-08-15 13:55
This is a dupe of https://github.com/lhorie/mithril.js/issues/1132

Would you mind sending in a PR for this? I figure we might as well start doing #1132 from somewhere

**Closed** 2016-08-15 16:05 UTC
