### ISSUE TITLE
[rewrite] Component recreated infinitely

### ISSUE THREAD

**Issue by sixmen** [lhorie/mithril.js#1404] opened 2016-11-18 09:04 UTC
### Description:

In Mithril 0.2.x, a component is always recreated when the route is changed,
but in rewrite, a component is not recreated if the route is same (e.x. changed from /items/1 to to /items/2), which is good in general.

But I want to recreate a component some time for freshness.

I questioned to Gitter, and I got an answer to use route resolver.
But when I try it, I got a strange behavior the component is recreated infinitely.

### Steps to Reproduce:

```
var Item = {
  oninit: function (vnode) {
    vnode.state.data = 0;
    m.request({
      method: 'GET',
      url: '/somerestapi'
    }).then(function () {
      vnode.state.data = vnode.attrs.id;
    })
  },
  view: function (vnode) {
    return m('div', 'Item'+vnode.attrs.id, m('br'), 'Data'+vnode.state.data, m('br'),
      m('button', {onclick: function () { m.route.set('/items/' + (Number(vnode.attrs.id)+1)) }}, 'Next')
    );
  }
};

var ItemRouteResolver = {
  onmatch: function (resolve, args, requestedPath) {
    resolve(Item);
  },
  render: function (vnode) {
    vnode.key = vnode.attrs.id
    return vnode;
  }
}

m.route(document.getElementById('app'), '/items/1', {
  //'/items/:id': Item
  '/items/:id': ItemRouteResolver
});
```

### Expected and Actual:

I want that 'Item' and 'Data' show the same number.
But 'Data' is not changed when I does not use route resolver.

And If I use route resolver, the browser request infinitely.
(I think the chain is request done -> render -> oninit called again -> request done -> render -> ...)

Is this a bug or do I need another pattern to achieve my purpose?

**Comment by lhorie** [comment] 2016-11-18 15:58
yes looks like a bug

**Comment by lhorie** [comment] 2016-12-01 06:51
Fixed in 713c25c9c0490a7f50368209148737bf76647dd7

**Closed by lhorie** 2016-12-01 06:51 UTC
Labels: bug

**Comment by pygy** [comment] 2016-12-03 11:31
@lhorie I'm surprised fixing this mandated a router rewrite, because 

1) after the first render, `oninit` fired *after* `view`, which should never happen and suggests a core bug and
2) the old `api/router.js` was only using the public APIs in ways user code would

http://jsbin.com/jedikajabu/edit?html,js,console,output (based on the last commit before the fix)

**Comment by lhorie** [comment] 2016-12-03 13:41
@pygy Can you expand on point 1)?

**Comment by pygy** [comment] 2016-12-03 13:53
Look at the log in the jsbin, I've yet to debug it...

```
    "resolve"
    "rrrender" // RouteResolverRender
    "init"
    "view"
    "async" // m.redraw()
    "rrrender"
    "view"
    "init"
```

**Comment by lhorie** [comment] 2016-12-03 13:55
ok thanks I'll take a look when I get a chance

**Comment by lhorie** [comment] 2016-12-03 14:10
@pygy update: bleeding edge does not appear to exhibit that behavior

**Comment by pygy** [comment] 2016-12-03 14:14
Even with the old router code? I suspect the router changes work around the actual bug. Or maybe it was fixed in the mean time?

**Comment by lhorie** [comment] 2016-12-03 14:23
@pygy On another note, the reason I rewrote that code was only marginally related to this issue. I felt that it was difficult to understand the back-and-forth flow with autoredraw.js and pubsub.js and hacks like root.redraw. It had occurred to me that it would be easier to understand the code if there was a dedicated redraw module as a dependency of mount and route.

The issue in 1404 itself was proving difficult to isolate, and rewriting helped me solve it by gradually adding in working code since gradually isolating faulty code wasn't getting me anywhere. There were also some other minor issues that got uncovered in the process (e.g. how incorrect parameter types were being handled). That process also uncovered a need for a flag in the core router module that did not exist before whose value didn't seem possible to infer from outside of the module

I'm aware that there are still some loose corners (e.g. the throttling), but I'm working on tightening them up. I hope you don't take it personally that I changed the code you wrote, I still find your contributions extremely valuable :)

**Comment by pygy** [comment] 2016-12-03 14:42
Re. the core router flag, been there, done that, but having `resolve(yeahReallyResolve)` as a signature seemed backwards, hence the mount-based approach I eventually picked, which doesn't require it. Building `route` on top of `mount` ensured that they both stayed in sync for things like debouncing.

**Comment by barneycarroll** [comment] 2016-12-03 15:51
I really like the notion that all managed redraws go via `m.mount` - this was also the basis of my abortive [route components](https://github.com/barneycarroll/mithril-route-components) work on `m.route` API.

There's a lot of potential in having one API through which all managed redraws work, since it can make custom application logic, plugins and monkey-patches far easier to reason about when layering functionality. This is, for instance, how [Exitable](https://github.com/barneycarroll/mithril.exitable.js) knows when to engage custom logic. Other exotic extensions to Mithril - like baking in the flux side-effect-enabling `context` APIs to components - would be made far more manageable if you know when a top level node is mounted.

**Comment by pygy** [comment] 2016-12-03 18:50
I don't take it personally, but I'm not happy to see a non-trivial contribution of mine wiped out with "fix foo" as a commit message when it was likely a symptom, not the cause.

For context, my GitHub account is literally my CV (I hold a medical degree, I have almost never coded professionally). I'll soon start looking for a dev job, and, assuming the router was not the culprit, it is a bit of a stain although it probably doesn't matter in the larger scheme of things. However this may explain why I'm this defensive...

That being said, if you judge the current approach better (regardless of the cause of the bug) then of course you should keep it.

A drawback (beside the weird internal API) is the fact that the [route matching logic](https://github.com/lhorie/mithril.js/blob/7368cf6f268825693c59caf4bfef67ef1a9bff56/router/router.js#L86-L108) runs for nothing on every redraw. No such thing with the mount-based code where redraws are the same as everywhere else, and resolution logic only runs when the router is summoned, either explicitly or implicitly by using history.

On the other hand the current code looks a bit terser than what I had, and you can probably fix the various kinks without bloating it past the size of the mount-based version.

**Comment by lhorie** [comment] 2016-12-04 04:12
@pygy if it makes you feel better, the majority of what was giving me trouble understand the logic flow was my own doing (autoredraw, pubsub, the convoluted dependency injection graph). It was a large refactor to clean up my messiness and your code just happened to be in the middle of the mix. I felt that depending on mount wasn't ideal (and I acknowledge that maybe I'm missing something and this is something we could discuss separately), but in the grand scheme of things, I think that's a minor point of contention.

Your intellectual and analytical contributions with regards to what constitutes correct onmatch resolution semantics are still there and strong, albeit w/ slightly different syntax, and in my opinion, the semantic analysis you did for that is far more valuable than the exact code constructs we're using in the implementations for the issues. 

Code changes naturally happen, but good analytical skills like yours are hard to find. If anyone ever wants to question the quality your contributions, I'll be more than happy to point them to docs/credits.md and make a recommendation if needed.

**Comment by pygy** [comment] 2016-12-04 14:29
@lhorie Thanks for the offer and the kind words, I was not disappointed by the disappearance of the code, more with the circumstances around it, but your praise more than makes up for it :-). I had noticed that you had preserved (most of) the semantics of my code, and I appreciate it, off course.

I understand it's important for you to know where the kids are... Keeping with local tradition for private code, I hadn't documented either the intent or the details.

I'll open an issue discussing the pros/cons of a mount-based approach (because, as you might have guessed, I still think it is superior, even though ultimately the best code is code that works and that *you* can maintain).

I'll also try to build a minimal, render-based repro for the `view => init` thing, if only to harden the test suite.

With `route` built on top of `mount`, I had thought of folding `throttle`, and `autoredraw` into `mount`, but since I didn't know the intent behind the code organization, I left it as is (I try to change as little as possible when I make a PR for easier reviews and to keep the code base as familiar to you as possible). `pubsub` looked like it could have had other uses (I don't remember which though).

After an initial "eeew", the `root.redraw` thing had grown on me for potential use from event handlers and request promise chains (even without #1157). AFAICT attaching them to `root` is the only non-contrieved way to make them accessible from `oncreate` hooks on first render.

**Comment by pygy** [comment] 2017-03-28 14:05
@lhorie There was a bug in the router... It was initially mounting a non-keyed `div` node and then redraw when the actual component was resolved. The non-keyed => keyed transition was causing the spurrious `oninit` and `oncreate` to fire after the `view` during the `update` phase. The latter was most likely a bug in `updateNodes` but it looks like it's been fixed in the mean time...

Here's a mount-based repro after the `api/*` refactor that still exhibits the issue:

http://jsbin.com/yejapuyeso/1/edit?html,js,console

`v1.1` doesn't have the bad `oninit` anymore.
