### ISSUE TITLE
Exceptions swallowed on controller requests

### ISSUE THREAD

**Issue by epidemian** [lhorie/mithril.js#1034] opened 2016-05-02 06:40 UTC
Hi! I noticed this behaviour in Mithril controllers and i was wondering if it is really a bug or if it's something expected. Consider this simple application:

```javascript
var Molecule = function(data) {
  this.name = data.name
  this.totalElements = data.elemetns.length // Typo!
}

var controller = function() {
  this.molecules = m.request({
    url: 'molecules.json', type: Molecule 
  })
}

var view = function(ctrl) {
  return [
    m('h1', 'Molecules'),
    ctrl.molecules().map(molecule => 
      m('li', `${molecule.name} (${molecule.totalElements} elements)`)
    )
  ]
}

m.mount(document.body, {controller, view})
```

Where `molecules.json` returns a silly JSON with something like:

```json
[
  {"name": "Water", "elements": ["Hidrogen", "Oxigen"]},
  {"name": "Ethanol", "elements": ["Carbon", "Hidrogen", "Oxigen"]}
]
```

Thing is, the application has a bug: a typo in the Molecule controller will cause `data.elemetns.length` to raise an exception when accessing the `length` property of an undefined value.

I would have expected to see an error like `TypeError: data.elemetns is undefined` logged to the console, but instead that error is swallowed and [the error logged to the console](https://plnkr.co/edit/yQRxtEe6ZZEON0CRH48t) is `TypeError: ctrl.molecules(...) is undefined` from the when the view code tries to access `ctrl.molecules().map`.

[The same thing happens](https://plnkr.co/edit/aDxEu6TCFRajTIjkLnSn) if instead of passing the option `type: Molecule` to `m.request`, a `.then` is used to convert the response to the Molecule type:

```javascript
var controller = function() {
  this.molecules = m.request({
    url: 'molecules.json' 
  }).then((data) =>
    data.map((d) => new Molecule(d))
  )
}
```

Again, the original exception is swallowed and `TypeError: ctrl.molecules(...) is undefined` is instead logged to the console.

*But*, if the request is made outside the controller:

```javascript
var Molecule = function(data) {
  this.name = data.name
  this.totalElements = data.elemetns.length // Typo!
}

// Start the request right away.
var molecules = m.request({
  url: 'molecules.json', type: Molecule 
})

var view = function() {
  return [
    m('h1', 'Molecules'),
    // Check molecules() existence for first render.
    molecules() && molecules().map(molecule => 
      m('li', `${molecule.name} (${molecule.totalElements} elements)`)
    )
  ]
}

m.mount(document.body, {view})
```

Then the original `TypeError: data.elemetns is undefined` [is logged to the console](https://plnkr.co/edit/crvLQmo8Mk6bIpVU3KQN), and the view code is not called a second time when the requests finishes. The rendering after the request seems to be cancelled because the request fails with an exception. Which seems like a reasonable behaviour, and makes me think that what's happening when the request is initiated on a controller might be a bug.

What do you think?

**Comment by isiahmeadows** [comment] 2016-05-02 23:27
Closing, since this is a duplicate of #968 and it's already been fixed in `next`. It was caused by a regression in [cb29a2](https://github.com/lhorie/mithril.js/commit/cb29a21ec308bf892dd01bd2e2c39711fa61150d), where I erroneously thought `m.deferred.onerror` was always called by the deferred in that particular step.

**Closed by isiahmeadows** 2016-05-02 23:27 UTC

**Comment by epidemian** [comment] 2016-05-02 23:49
Thanks for quick resolution @isiahmeadows! 

(Damn, if i looked for previous reports of this, i must have done a very bad job at it; the title is almost the same! Now i don't know if i did :sweat: )

**Comment by isiahmeadows** [comment] 2016-05-03 02:03
@epidemian You're okay! :smile:
