### ISSUE TITLE
ES2015 classes cannot be used with Mithril

### ISSUE THREAD

**Issue by isiahmeadows** [lhorie/mithril.js#735] opened 2015-07-25 20:38 UTC
Basically, [this line](https://github.com/lhorie/mithril.js/blob/next/mithril.js#L724) will throw in any ES2015 class implemented with correct semantics. The problem is that you can only `.bind` classes; you can't `.apply` or `call` them with anything. In io.js 2.4.0, which does implement correct semantics (Babel can't due to ES5 restrictions):

```
> class F {}; F.apply(Object.create(F.prototype))
TypeError: Class constructors cannot be invoked without 'new'
    at new F (repl:1:23)
    at repl:1:37
    at REPLServer.defaultEval (repl.js:154:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:308:12)
    at emitOne (events.js:77:13)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
    at REPLServer.Interface._line (readline.js:549:8)
```

**Comment by impinball** [comment] 2015-07-25 20:43
Same thing with Chrome in strict mode + `#enable-javascript-harmony`:

```
> (function() { 'use strict'; class F {}; return F.apply(Object.create(F.prototype)) })()
Uncaught TypeError: Class constructors cannot be invoked without 'new'
    at new F (<anonymous>:2:29)
    at <anonymous>:2:50
    at <anonymous>:2:86
    at Object.InjectedScript._evaluateOn (<anonymous>:905:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:838:34)
    at Object.InjectedScript.evaluate (<anonymous>:694:21)
```

**Comment by Naddiseo** [comment] 2015-07-27 18:04
Duplicate of #618 ?

**Comment by impinball** [comment] 2015-07-27 21:16
No. Consider this blocking that bug. This is limited to merely ES6 classes
for "component".

**Comment by impinball** [comment] 2015-07-27 21:31
Clarification: the "component" property.

**Comment by impinball** [comment] 2015-07-27 21:35
s/component/controller/g...
What I mean is this is supposed to work:

```js
var component = {
  controller: class { /* ... */ },
  view(ctrl) { /* ... */ },
}
```

**Comment by Naddiseo** [comment] 2015-07-27 23:07
```js
var component = {
  controller: class { /* ... */ },
  view(ctrl) { /* ... */ },
}
```

That *does* work.. at least in chrome 43: https://jsfiddle.net/wv5jfoyh/

And if you mean not working with `m.component`, that's exactly what #618 is about.

**Comment by lhorie** [comment] 2015-12-21 00:32
reading again, this does look like a dupe of #618 to me, so I'm closing this

**Closed by lhorie** 2015-12-21 00:32 UTC
