### ISSUE TITLE
ospec chokes trying to import a file that uses the ** operator

### ISSUE THREAD

**Issue by IBwWG** [lhorie/mithril.js#1703] opened 2017-03-11 10:05 UTC
Mithril 1.0.1.

I had been using `Math.pow`, then switched to `**` on the advice of airbnb's eslint defaults.

Now running ospec gives a syntax error:

```
$ npm test

> cheatermind@1.0.0 test /home/kev/projects/cheatermind
> ospec

/home/kev/projects/cheatermind/src/js/AI.js:9
  const possibilities = colours ** slots;
                                 ^
SyntaxError: Unexpected token *
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/kev/projects/cheatermind/tests/diff.js:5:9)
    at Module._compile (module.js:570:32)
npm ERR! Test failed.  See above for more details.
```

The test file gets there via this:

```js
"use strict"

var o = require("../node_modules/mithril/ospec")

var a = require("../src/js/AI")

a.init(4, 6)
```

**Comment by IBwWG** [comment] 2017-03-11 10:09
They made the change here: https://github.com/airbnb/javascript/commit/1399b3cbfa785f760c15ec63112f711b2c68fd28

The comments indicate it's an ES2017 thing.  I'm not sure the rationale for not allowing the old way, though.

**Comment by IBwWG** [comment] 2017-03-11 10:10
Workaround:

```js
  const possibilities = Math.pow(colours, slots); // eslint-disable-line no-restricted-properties
```

**Comment by pygy** [comment] 2017-03-11 18:04
What node version are you using? What `ospec` version?

Did you try launching the test file without the `ospec` runner?

**Comment by isiahmeadows** [comment] 2017-03-12 05:41
@IBwWG 

Two options:

1. Use Node 7.6 or later, where it's enabled by default.
2. Use Node 6.5 or later with `--harmony-exponentiation-operator`.

Either way, it's not a bug in ospec, so I'm closing.

**Comment by isiahmeadows** [comment] 2017-03-12 05:41
Or, option 3: just use `Math.pow` in the meantime.

**Closed by isiahmeadows** 2017-03-12 05:41 UTC

**Comment by isiahmeadows** [comment] 2017-03-12 05:42
Or, option 3: just use `Math.pow` in the meantime.

**Comment by IBwWG** [comment] 2017-03-13 07:15
Sorry, I didn't realize this was the case.  Thanks for detailing the options :)
