### ISSUE TITLE
onunload called multiple times with m.component()

### ISSUE THREAD

**Issue by mikegleasonjr** [lhorie/mithril.js#931] opened 2016-01-13 09:01 UTC
If the page is redrawn 3 times, onunload will be called 3 times for each `m.component()`

I created a simple test case to reproduce:

```js
var Component = {
  controller: function() {
    console.log('Component controller')
    this.onunload = console.log.bind(console, 'Component onunload');
  },
  view: function(ctrl, args) {
    return m('h1', 'component')
  }
}

var Home = {
  controller: function() {
    this.onunload = console.log.bind(console, 'Home onunload');
  },
  view: function(ctrl, args) {
    return m.component(Component);
  }
}

var Page2 = {
  view: function(ctrl, args) {
    return m("h1", "page2")
  }
}

m.route(document.body, "/", {
  "/": Home,
  "/page2": Page2
});

setTimeout(m.redraw.bind(m));
setTimeout(m.redraw.bind(m));
setTimeout(m.route.bind(m, '/page2'), 1000)
```

Will print:

```js
Component controller
Component onunload Object {}
Component onunload Object {}
Component onunload Object {}
Home onunload Object {}
```

https://jsfiddle.net/fx5t34h1/30/

**Comment by isiahmeadows** [comment] 2016-01-13 09:16
PRs welcome. Looks like a bug to me (onunload should only be called once).

**Comment by mikegleasonjr** [comment] 2016-01-13 09:24
I'd like to learn the in and outs of Mithril to help, any kickstarter documents to suggest before reading the code?

**Comment by nordfjord** [comment] 2016-01-13 11:04
I had already made a PR for this #877 which was merged but seems to have been removed, my solution was to remove the controller and view from their respective arrays when unload was run, since in my view an unload should be final.

**Comment by isiahmeadows** [comment] 2016-01-13 23:14
@mikegleasonjr Not really.

@nordfjord If it was, then it was likely removed by accident. Go ahead and send a new PR. (Just make sure it's 100% tested to ensure this bug doesn't crop up again.)

**Comment by lhorie** [comment] 2016-01-13 23:40
@nordfjord @isiahmeadows FYI, it wasn't removed by accident. It turned out that that PR caused a bunch errors in the old test suite and was one of the things that caused problems in the 0.2.1 release, so I had to revert it.

**Comment by nordfjord** [comment] 2016-01-14 12:46
@lhorie Didn't realize the old test suite wasn't run anymore, I'll get on this again when I have free time.

You have my deepest apologies.

**Comment by lhorie** [comment] 2016-01-14 16:46
@nordfjord no worries, I should've caught it earlier. Thanks for the help!

**Comment by isiahmeadows** [comment] 2016-01-14 20:29
@lhorie If I had caught it in my refactoring, I would've kept it. It was an accident of ignorance by me.

**Comment by isiahmeadows** [comment] 2016-01-22 16:57
@lhorie And it helps if I can read... :frowning: 

I was looking back at this trying to find ways to fix the currently broken tests from an in-sync `next`.

**Comment by Morklympious** [comment] 2016-02-25 22:30
I'm looking at a stack trace of `updateLists`, and it looks like the component is added to `unloaders `multiple times, then added to `views` and `controllers` arrays. [Seen here](https://github.com/lhorie/mithril.js/blob/next/mithril.js#L751-L761)

calling `m.redraw` (or `m.redraw.bind(m)` as seen in the fiddle) causes the `unloaders` array to have an item pushed to it during the call to `updateLists`, however, _prior_ in the stack trace, `buildObject` is called, assigning both `views` and `controllers` arrays to empty arrays. [Seen here](https://github.com/lhorie/mithril.js/blob/next/mithril.js#L801-L802)

So essentially, after every redraw, you're looking at another call to build object, which wipes `views` and `controllers`, but the call to `updateLists` only adds more things to the array. Worth mentioning that these things aren't added to the `unloaders` array unless they have an `onunload` property in the controller. 

I think the solution to the problem is to just find an appropriate place to wipe unloaders. there's likely something I'm missing here in terms of understanding, so I'll keep looking around, but the reason there are three `console.log` statements after the redraws and the reroute is because **an `unloaders` item is added to unloaders that is never removed every draw** and it's added because `this.onunload` isn't null in the controller. 

Stack trace from `m.redraw` for reference:

`updateLists`
`checkView`
`markViews`
`buildObject`
`build`
`m.render`
`(anonymous function)`
`forEach`
`redraw`
`m.redraw`
`...`

**Comment by nordfjord** [comment] 2016-02-26 01:20
I've been getting around this using:

```js
ctrl.onunload = _once(function(){
  // do actual unloading
});
```

meaning the controller's onunload can only be executed once. Perhaps we could make a temporary fix involving something along these lines:

```js
function _unloadOnce(fn) {
  var unload = function (ev) {
    if (!unload.executed) {
      unload.executed = true;
      fn(ev);
    }
  };
  unload.$once = true;
  return unload;
}

// after preventDefault calls
unload.executed = false; 

// inside updateLists
if (type.call(ctrl.onunload) === FUNCTION && !ctrl.onunload.$once) {
  ctrl.onunload = _unloadOnce(ctrl.onunload);
}
```

**Comment by lhorie** [comment] 2016-02-26 01:28
I took a look, and implemented a change to prevent duplicate entries in the unloaders array

**Closed by lhorie** 2016-02-26 01:28 UTC
Labels: bug, contribution welcome

**Comment by nordfjord** [comment] 2016-02-26 01:32
Well... that was simple :)
