### ISSUE TITLE
Bug with keys causing extra duplicate elements to appear since v0.31

### ISSUE THREAD

**Issue by farzher** [lhorie/mithril.js#533] opened 2015-04-04 07:34 UTC
Code to replicate

```
i = 0
noop = function(){}

m.module(document.body, {
  view: function() {
    return [m('input', {key: i++, onkeyup: noop, onblur: noop})]
  }
})

```
http://codepen.io/farzher/pen/YPMmRB?editors=101

Type into the input box

**Comment by barneycarroll** [comment] 2015-04-04 14:14
One of the problems with Mithril is that since I've been using it, everything has been a patch update, ie v0.1.X. Combine this with the fact that commits are rarely linked to the issues they solve and you're left with a situation where it's really difficult to work out what version you should be using, or more specifically what the scope of any given release is.

I've mentioned before that I'm particularly uncomfortable with the way components branch uses the key API under the hood for controller instance management, and yet despite the single-expression components invocation feature having its own branch, I can't help but suspect a lot of these weird regressions are to do with supporting this functionality — I've been watching the Mithril issues feed religiously and I can't recall any reason why DOM diffing and specifically key logic would have needed to change in these areas according to current matter branch remit.

I remember remarking that it was really impressive that Mithril version control worked so smoothly despite all the functionality being in a single monolithic file, but I suspect this is one of the cracks of such an approach: in order to stay manageable, the components branch has to have parts of its functionality regularly merged into master to avoid too much disparity when it finally reaches completion.

I'm not going to go trawling through the commit history to work out when the documentation for `key` removed the notice to avoid using it except in special circumstances but I would assert that this is the case now more than ever.

**Comment by webcss** [comment] 2015-04-04 16:56
@farzher Excuse my ignorance, but why would someone want to do that, increment the key with every redraw cycle? I think this is exspected behaviour since the key property is there to make elements identifyable. This is especially necessary for lists, where items are added, changed and removed. For a single input item this makes no sense, since it stays in virtual dom, and you increment its key it behaves like a listitem added and duplicates the input element, or any other element on redraw.

**Comment by farzher** [comment] 2015-04-04 17:02
@webcss Well, it definitely isn't expected behavior. I'm asking to draw 1 input, so it shouldn't keep getting extra elements stuck in the dom.
This is a simplified test case. I got this bug trying to implement [TodoMVC](https://github.com/farzher/mithril-livescript-todomvc). Each element needs a unique key or it bugs out, so I just iterated the keys so they're always unique. Which works in older versions of mithil, but made duplicate elements in current mithril.

**Comment by webcss** [comment] 2015-04-04 17:57
@farzher Ok, maybe it was a bug with the older versions? you shouldn't want to increment any value within the view, which is the same as instanciating the controller within the view, which is considered bad practice with unforeseeable behaviour since the earliest version. You would generate a key just once, for immutability.

**Comment by farzher** [comment] 2015-04-04 18:08
@webcss I always want a new unique key, that's why I'm incrementing.
I'm trying to say "Please remove the old element and insert a new one instead of diffing"
Seems reasonable to me (it's just a little lazy and worse performance)

**Comment by webcss** [comment] 2015-04-04 18:45
Ok, I see what you mean. Until 0.1.30 it works as you want. While I haven't found the source for this issue, I have a workaround for you:
```javascript
i = 0
noop = function(){}

m.module(document.body, {
  view: function(scope) {
    var v= [
      m('input', {key: i, onkeyup: noop, onblur: noop}),
           m('p', i)];
    i++;
    return v;
  }
})
```

**Comment by farzher** [comment] 2015-04-04 19:01
? That doesn't fix it for me. It still puts extra inputs at the bottom

**Comment by webcss** [comment] 2015-04-04 19:09
oops, sorry, forget about that, still had 0.1.30 setup in codepen.

**Comment by webcss** [comment] 2015-04-04 23:01
Ok, problem seems to be only existent with current next branch. I've replicated your codepen using both, next and component branch. next behaves as you describe, while component branch will work as you expect it to.

**Comment by lhorie** [comment] 2015-04-19 03:06
This is already fixed in components branch, so I'm gonna close this

**Closed by lhorie** 2015-04-19 03:06 UTC
Labels: bug
