### ISSUE TITLE
How to preserve css animation between renders

### ISSUE THREAD

**Issue by eguneys** [lhorie/mithril.js#911] opened 2015-12-21 14:05 UTC
I am building a game, with css animations.

I have this css rule for move animation:

    .animate {
      animation: play-move 1s steps(10) infinite;
    }

I update my state every half second so state changes as:

1. State: `[0, 1, 0]`
View: `<div/><div class="animate"/><div />`
2. State: `[0, 0, 1]`
View: `<div/><div/><div class="animate">`

The problem is as the dom changes, the css animation resets, so I can't see the full animation.

see fiddle:
http://jsfiddle.net/CGmCe/12968/

I tried adding key attribute to `div`s but that did nothing.

**Comment by eguneys** [comment] 2015-12-21 15:31
Here's the mithril version: http://jsfiddle.net/CGmCe/12982/

**Comment by lhorie** [comment] 2015-12-22 13:37
as far as I can tell, it's because you're not changing the key to follow the animate class, i.e. the first element always has key = 1, second always has key = 2, etc, as opposed to rotating in sync w/ the animate class

**Comment by eguneys** [comment] 2015-12-22 14:26
@lhorie I fixed the key issue, now it works fine here: http://jsfiddle.net/CGmCe/12990/.

except when it goes backwards it resets again see http://jsfiddle.net/CGmCe/12991/.

**Comment by eguneys** [comment] 2015-12-29 14:19
@isiahmeadows  Is this a bug, can you explain why how does this happen. I've tried with react and v-dom and both have the same problem.

React: http://jsfiddle.net/CGmCe/12998/

v-dom: https://gist.github.com/eguneys/49121fe67079d1f72554

**Comment by leeoniya** [comment] 2015-12-29 14:52
> except when it goes backwards it resets again see http://jsfiddle.net/CGmCe/12991/.

the problem is actually the opposite. it resets on every frame *except* the last one. so when it wraps around it's actually finishing the animation it started before. if you change the delay to 1000 you see that it goes away. looks like an issue with keyed DOM element re-use/reordering.

**Comment by eguneys** [comment] 2015-12-29 16:23
@leenoiya, how should I render my data to fix this? Can you update the jsfiddle so it works please. Thanks.

I have this array: `[1, 2, 3, 4, 5];`
And I map over this:
`
  for (var i = 0; i<area.length; i++) {
   children.push(renderTile(i));
  }
`

Whenever I encounter a 1, I add the "animate" class. So the problem is position of `1` changes, so does the DOM order.

I might sort the array by the key, to keep the order same, but I have to dynamically add remove children too, so DOM order will change no matter what. The problem is not "moving" the frame, i don't understand how css transform will help.

I need a guarantee that the elements with the same keys should not be removed ever.

**Comment by leeoniya** [comment] 2015-12-29 16:53
You would have only a single `.tile` instead of 5. On each loop you simply set its css `transform: translate(50px, 0);` where the 50px x-offset is recalculated each time to re-position the sprite where you want in the container.

**Comment by leeoniya** [comment] 2015-12-29 17:07
all that being said...

you're probably much better off using the right tool for the job. there are several great, lightweight sprite frameworks that have all of this (and much more) already handled.

http://darsa.in/motio/
http://spritely.net/
https://github.com/batiste/sprite.js/

**Comment by eguneys** [comment] 2015-12-29 20:24
@leeoniya, each array element is a different tile so I have to render them all. Even If I use transform property, They still have an order on the dom. As I shuffle the items in the array, add/remove tiles, the order changes, and animation resets.

**Comment by leeoniya** [comment] 2015-12-29 21:03
then don't reorder them in the dom. use the array as the sort order to just calculate the correct css transform offsets for each of them.

look at how this works: http://vestride.github.io/Shuffle/

the dom elements never move. the lib just recalculates their sizes and positions then adjusts the css transforms on each.

**Comment by lhorie** [comment] 2016-06-03 20:20
Not sure why this is marked as bug. Looks more like a question. Closing

**Closed by lhorie** 2016-06-03 20:20 UTC
Labels: question
