### ISSUE TITLE
v0.2.5 select[multiple] got broken

### ISSUE THREAD

**Issue by pelmenept** [lhorie/mithril.js#1135] opened 2016-07-03 01:51 UTC
### Description:

m('select[multiple')
Returns "select" field without "multiple" attribute - basically a dropdown.
Any other attribute works fine

**Comment by sebastiansandqvist** [comment] 2016-07-03 08:40
If it's just that this is a typo then this should fix it: `m('select[multiple]')`

**Comment by pelmenept** [comment] 2016-07-03 16:20
Sorry it's just a typo in the issue report. In my js I have it correct as m('select[multiple]'). 

I tested with 0.2.5(does not work) and 0.2.4(works fine). I had to revert back to 0.2.4.

**Comment by curist** [comment] 2016-07-04 03:59
Neither 0.2.5 nor 0.2.4 works for me, but by using

    m('select[multiple=foo]')

it works.

**Comment by isiahmeadows** [comment] 2016-07-06 21:17
@curist Closing as a duplicate of #1093, and it should be fixed in 3cf1663. The fix hasn't made it to npm yet, but as a short-term workaround, try `m("select[multiple=]")` (note the equal sign). If the bundle in `next` doesn't fix this, I'll re-open it.

**Closed by isiahmeadows** 2016-07-06 21:17 UTC
