### ISSUE TITLE
Don't conflate string uniqueness with DOM uniqueness to determine controller identity

### ISSUE THREAD

**Issue by barneycarroll** [lhorie/mithril.js#514] opened 2015-03-24 03:31 UTC
This issue relates to [Components branch](https://github.com/lhorie/mithril.js/tree/components) and the ability to easily invoke modules in any given view without the need to compromise application architecture.

* The application development framework should not defer to authors the necessity to manage unique string keys for each globally distinct component in play.
* Binding controllers to distinct DOM elements invalidates some of the most powerful features of Mithril as exemplified by [the exercise in awesomeness](http://lhorie.github.io/mithril-blog/an-exercise-in-awesomeness.html): the separation of DOM identity from context is one of Mithril's greatest strengths, both in terms of performance and developer convenience.
* Insisting on a unique DOM node per component encourages wrapping and hierarchical architecture which blocks the benefits of creating contexts at will and giving them the content they necessitate. This in turn invalidates the notion of composability and wider agnosticism, and makes it harder to write general purpose plugins.

[Modulator's](https://gist.github.com/barneycarroll/0e3c1b9811b47c012b13) API may be of dubious value, but the internals show that it is possible – without access to Mithril internals – to keep controller instances both more distinct and more flexible with less developer overhead and limitations. The same principles used in polyfilling Maps can be implemented in Mithril trivially without the need to constrain author power. The only question is API.

**Comment by markmarijnissen** [comment] 2015-03-24 09:07
So, to reformulate, the central question is:

* How to instantiate multiple controllers to a single element?

Where you make the following points:

* Authors should not be burdened by generating globally unique strings for their controllers. You prefer to limit keys to a certain scope, i.e. generate identifiers based on context + key (rather than having an implicit global context and using a global key). 
* An element should be able to have multiple controllers to facilitate composability (i.e. jQuery-style "plugins", Mixins, behaviors, angularjs-style "directives"). The component-branch only allows a single controller per view.

The Modulator deals with the following issues:

* Scope: Global instance (shared in multiple views) -vs- local instance (one per view) -vs- ....?
* Lifecycle: With module lifecycle -vs- once-per-redraw (for controller-less modules?) -vs- ....?

I'm wondering - in functional programming, you can composite using `f(g(h(x)))` - which is the Modulator API. But often, there is also do `compose(f,g,h)(x)`.

So might it be a better API to have some kind of `compose` function which takes multiple modules and returns a single module? There needs to be some way to configure scope and lifecycle - which I guess is what the real difficulty is about.

**Comment by markmarijnissen** [comment] 2015-03-24 09:08
And please, correct me if I am wrong. I have a sense I am not fully grasping the problem yet!

**Comment by lhorie** [comment] 2015-03-24 13:26
@markmarijnissen multiple controllers per dom element can be done using a "mixin" pattern

```javascript
var multi = function(module, mixins) {
  return {
    controller: function() {
      var controller = new module.controller(...arguments)
      var ctrl = new controller
      args.forEach(function(module) {
        Object.assign(ctrl, new module.controller(...arguments))
      })
      return ctrl
    },
    view: module.view
  }
}
```

I believe this proposal is more analogous to Angular directive's `controller` option. There, a single controller can be shared between multiple directives. The `form` directive, for example, does use string-based identity (via the HTML `name` attribute) to create the sharing relationship (for things like $scope and the validation API)

To achieve this in Mithril, you could use the factory pattern:

```javascript
var SharedController = function() {
  this.foo = "bar"
}

var SharedControllerFactory = function() {
  //I'm just using regular maps here, but could be a WeakMap
  //or you could use a WeakSet if you're injecting the controller instead of creating one from a factory
  var controllers = {}
  return function(options) {
    return controllers[options.name] = controllers[id] || new Shared()
  }
}.call()

var SharedComponent = {
  controller: SharedControllerFactory,
  view: function() {...}
}

//in the view
m("div", m.module(SharedComponent, {name: "foo"}))
```

My general opinion of this is that, yes, there are a bunch of things that are not in core and that are useful in certain situations, but that would turn Mithril into Angular complexity-wise if they were.

**Comment by tivac** [comment] 2015-03-24 17:55
> My general opinion of this is that, yes, there are a bunch of things that are not in core and that are useful in certain situations, but that would turn Mithril into Angular complexity-wise if they were.

I cannot give this enough :+1:s

**Comment by barneycarroll** [comment] 2015-03-24 18:25
It's also completely at odds with what this issue is about. These implementation details are a convenience in core but they are not ostensible conveniences to the end user — quite the opposite: they are arbitrary restrictions. It's a fallacy to assert that enabling authors to write plug and play components that generate siblings or simply transform the output of other components forces complexity on the end user. Modulator proves that these considerations do not need to be forced on the end user if they do not want to use them.

Meanwhile, I'm looking at an increasing number of components of my own making that are incompatible with components branch.

The reason I bring this up is because I care deeply about the future Mithril ecosystem. I don't want to be in a position in a year or two's time where Mithril users learn canonical Mithril but then have to ditch m.module and learn alternative methods for doing essentially the same thing (minus arbitrary restrictions) if they want to use occlusion culler or transformation components. Moreover, this would end up with unnecessary cognitive load and implementation cruft in user land: powerful plugins like these, which magic away complicated engineering problems that users could well do without, would need to have special usage instructions: you can't use Mithril's in-built component management with this plugin: use this other one instead.

For the sake of example, [here are](http://jsfiddle.net/barney/bkcqncpa/) some [nifty components](http://jsfiddle.net/barney/g3zudyd3/) that are incompatible with components branch because of these restrictions.

We've discussed API elegance elsewhere and you expressed a preference for config objects compared to Modulator's functor signature. That's fair enough — I'm not insisting Mithril components needs to adopt Modulator's signature. What I am saying is that Modulator's internal logic — which handles any level of identity complexity without forcing unique root elements per component it forcing the user to manage globally unique keys — is very useful functionality that Mithril components will suffer without.

**Comment by lhorie** [comment] 2015-03-24 19:16
Are they really incompatible? Quickly looking at, e.g. `bidi`, it seems like something that is perfectly possible to implement, e.g.

```javascript
var Bidi = {
    view : function( ctrl, attrs, node ) {
        //simplified for brevity
        var prop = attrs.bind
        if( type === 'select' ){
            node.attrs.onchange = function( e ){
                prop( this.selectedOptions[ 0 ].value );
            };
        }
        else if( type === 'checkbox' ){
            node.attrs.onchange = function( e ){
                prop( this.checked )
            };
        }
        return node
    }
}

//using it
m("div", [
  m.module(Bidi, {bind: foo}, m("select", ...))
])
```

**Comment by barneycarroll** [comment] 2015-03-24 19:43
You're right — it's perfectly usable. That was a mislink to the occlusion culler, which I haven't actually put out yet (because it still isn't completely plug and play as a component yet). More fool me. Do you see the difference between internal implementation complexity and API complexity though?

**Comment by lhorie** [comment] 2015-03-25 00:41
To be honest, it's still not clear to me what this thread is about. AFAIK, the positional identity semantics in the components branch are working as intended and passing all the tests that I could think of throwing at it.

We could keep talking about how Modulator does X and Y, and how components branch does W and Z, but unless there's a problem in the components branch API, I'm inclined to close this issue.

**Comment by lawrence-dol** [comment] 2015-03-25 03:07
Forgive me if I am missing the point, but...

> The application development framework should not defer to authors the necessity to manage unique string keys for each globally distinct component in play.

It's my understanding that the key need only be unique within the parent using the component. That is not a globally unique key, but a segregated one. It seems reasonable for me for the parent to provide a key should it choose to use multiple instances of a given component.

> Insisting on a unique DOM node per component...

I am not seeing anything prohibitive in requiring a single container element for a component; I think this objection need to be illustrated with examples of when this would be undesirable.

**Closed** 2015-03-30 17:36 UTC
