### ISSUE TITLE
using config/!isInitialized to mimic view constructors is clunky

### ISSUE THREAD

**Issue by leeoniya** [lhorie/mithril.js#492] opened 2015-03-17 15:44 UTC
this code from the components docs:

```js
    view: function(ctrl, args) {
        return m(".uploader", {
            config: function(element, isInitialized) {
                if (!isInitialized) {
                    Uploader.dragdrop(element, {onchange: args.onchange})
                }
            }
        })
    }
```

would it be possible to additionally define a `init` key beside the `config` so that it can be used more cleanly instead of having to wrap & nest all initial constructor logic inside a config/!iisInitialized pyramid. it seems like a fairly common case to make easier, imo. the config can be invoked every time, but the init would just be invoked when `isInitialized` would be false. so...

```js
    view: function(ctrl, args) {
        return m(".uploader", {
            init: function(element) {
                    Uploader.dragdrop(element, {onchange: args.onchange})
            },
            config: function(element){/*  */}
        })
    }
```

it's a bit late in the game, but it would be nice to rename `controller` to `constructor`, or `init` in the modules too to maintain uniformity with the suggested view constructor naming. i was a bit baffled by the naming, since all it is is a module's constructor. I know it's from `MVC`, but in Mithril's case there's pretty much no reason to name it `controller` when it literally is the `constructor` and nothing more. all the view binding is closer to MVVM where the views reference models through the module/ctrl.

thanks!

**Comment by leeoniya** [comment] 2015-03-17 16:12
> I know it's from MVC, but in Mithril's case there's pretty much no reason to name it controller when it literally is the constructor and nothing more.

guess i'm not the first to point this out :)

https://groups.google.com/forum/#!topic/mithriljs/t4eH7ycl5DM

**Comment by barneycarroll** [comment] 2015-03-17 16:25
@leeoniya a while back I wrote a little utility for this (my Mithril toolbelt is full of little utilities with limited scope):
```javascript
function onReady( fn ){
  return function config( el, init, ctxt ){
    if( !init ) fn.call( this, el, init, ctxt );
  };
}
// In use:
m( 'thing', {
  config : onReady( myAwesomePlugin )
} );
```
The thing is I found that most of my config plugins expanded over time to include behaviour that needed to happen outside of init as well. In the end I found it more convenient to ditch it. One of the main concerns is that my config plugins usually sit in their own files elsewhere, and often I won't know from the view whether the plugin does stuff on each redraw or only on init – and writing a plugin with the explicit caveat that it must only be invoked onload is a pretty cruel requirement. So I usually just bite the bullet on this one.

**Comment by leeoniya** [comment] 2015-03-17 16:42
i haven't looked too deeply into https://github.com/Raynos/mercury yet, but from glancing at the docs, the naming conventions and patterns seem to make a lot more sense to me. Mithril's BC concerns may be too great to change things drastically at this point.

**Comment by barneycarroll** [comment] 2015-03-17 16:44
> BC concerns

What are those?

Personally I think the tiny API surface is one of Mithril's  great assets. Other frameworks have so many methods to save you half a line of code, it just ends up confusing.

**Comment by lhorie** [comment] 2015-03-17 17:31
BC = backwards compatibility

@leeoniya FYI, there's going to be a breaking change when I move to the ES6 promise API. I'm open to introducing other breaking changes to the API at that point.

**Comment by kvanberendonck** [comment] 2015-03-18 04:32
@lhorie this is an opportunity for an optimization. This means we can have `init` without `config`, so the hot path won't call a `config` doing nothing.

**Comment by lawrence-dol** [comment] 2015-03-18 20:24
@lhorie : I think I would prefer to have breaking changes introduced one at a time during successive 0.x releases, than have a whole bunch of them land at once. 

At 1.0 the focus should shift on maintaining backwards compatibility, but 0.x is the time to experiment with the API, keep what's good and throw out what's not and to get the concepts and naming solidified.

Just my 2 cents -- and I have production code deployed with Mithril and plan on creating a lot more, so I am invested in the framework.

**Comment by lhorie** [comment] 2015-03-25 03:14
@lawrence-dol the ideal migration path for me would be that all breaking changes be exhaustively documented, be easily greppable (is that a word?) and that I could do such a migration in one shot. 

Personally, I was left with a bad taste in my mouth when Angular would randomly break things release after release (especially when it would break things that weren't obvious until you actually ran a specific part of the app that happened to use a specific idiom)

Basically, you had to pick between sticking w/ an old version w/ known issues and missing features, or biting the bullet and invest a relatively significant amount of time on a mini-migration effort (which would at a minimum involve covering the cases documented in the change log and then smoke test the entire app for regressions because who knows what the more cryptic notes mean). And all that only to find out that you're back in a similar situation a month later...

Compare to jQuery 1.x -> 2.x. It was thoroughly documented and with a notice well in advance, with a clear commitment strategy to support both the 2.0 folks as well as the legacy folks.

In summary, even if I or you might think that a particular breaking change is small, it actually might be a big deal (because it might be something that is used a lot by someone w/ a really large codebase, or maybe because someone lacks the test infrastructure to be confident after a migration, or maybe because the company doesn't share our opinions on the value of upgrading a framework vs cranking out features), so I think it needs to be treated as a big deal.

Also, I'd like to get the process for breaking changes nailed down early, rather than be pulling an Angular w/ random breaking changes after 1.x

**Comment by lawrence-dol** [comment] 2015-03-25 03:39
@lhorie I completely concur. Whenever at all possible a breaking change should be done by first introducing the new thing and deprecating the old and that should be clearly documented in a separate list somewhere so that I can go to that list and see everything for which a different better way now exists. Then only at a major version increment should deprecated things be removed and that should be in the aforementioned list. This provides a window of time to migrate old code.

The exception is version 0.x where the major design and API elements are hashed out, often only by trying them in real code and discovering that what seemed good in theory was not so much so in practice. But that should not be taken as license to break things constantly. 

The best API is the one that works well forever. But a common mistake is to accept long-term cruft over long-term elegance -- for Mithril part of it's elegance is small footprint. And, in truth, there is not much that needs to happen to Mithril after components are landed (my contentions about MVx notwithstanding).

I support you in the idea that Mithril should be slow to bake things into the core, and slow to deprecate and remove things; but it would be a mistake to never recognize when things need to be removed.

**Comment by markmarijnissen** [comment] 2015-03-25 20:28
I am totally in favor of breaking changes in the 0.x releases. That is what they are for, and as consumer of a library I a well aware of the risk. I prefer fast, flexible development over stable, production-quality code. I really don't like a library being stuck / slow to change without even reaching 1.0.

I accept any refactoring of the API. Also, I accept responsibility of properly testing my app - i.e. when breaking changes are announced I should not assume my app just works after blindly changing the code.

My opinion being said, what about maintaining two branches?

- A stable branch which gets all improvements and bugfixes.
- An unstable branch which gets all new functions and API changes.

**Comment by barneycarroll** [comment] 2015-03-25 20:39
@markmarijnissen I think that's a practical problem because all of Mithril is one monolithic file: merging changes in from one branch to another takes dedicated work because there's no per-file separation of concerns. But I think it would be really silly to maintain 0.1 and 0.2 versions. The API changes in question are just a question of replacing method calls in application code — it would be unreasonable for a developer to expect new features and bug fixes for eternity by updating a dependency while refusing to change API hooks in their own code.

**Comment by lhorie** [comment] 2015-03-26 03:38
> I accept any refactoring of the API. Also, I accept responsibility of properly testing my app - i.e. when breaking changes are announced I should not assume my app just works after blindly changing the code.

Right. The social contract during 0.x versions is that all bets are off wrt to API stability, but all I'm saying is that I want to avoid having you guys coding against a constantly moving target, and instead have documented milestones.

FWIW, my current workflow is that bug fixes go in the `next` branch and the next major milestone is in the `components` branch (with `next` being periodically merged into it).

I don't think the number of files makes much difference in how difficult it is to support multiple concurrent versions, since diffing is per line of code anyways. Having feature branches *should* allow me to theoretically support multiple versions concurrently, but I probably won't have the patience or the time to be supporting more than two at any given time.

**Comment by lhorie** [comment] 2016-06-01 20:28
re: initial concern: the rewrite branch now has oninit / oncreate / onupdate to give more granular control

**Closed by lhorie** 2016-06-01 20:28 UTC
Labels: breaking change proposal, discussion
