### ISSUE TITLE
Broken edge case for Components branch?

### ISSUE THREAD

**Issue by mindeavor** [lhorie/mithril.js#466] opened 2015-02-24 05:19 UTC
I ran into this while using the `components` branch to develop an app. Basically I was trying to render lvl 3 nested components from within a lvl 2 nested component. The lvl 3 components have keys, while the lvl 2 does not:

```javascript
test(function() {
  // nested components under keyed components should render
  mock.requestAnimationFrame.$resolve()

  var root = mock.document.createElement("div")
  var count = 0
  var module = {
    controller: function() {},
    view: function(ctrl) {
      return m.module(sub, { list: [1, 2, 3] })
    }
  }
  var sub = {
    controller: function() {},
    view: function(ctrl, props) {
      return props.list.map(function(i) {
        return m.module(subsub, {key: i})
      })
    }
  }
  var subsub = {
    controller: function() {},
    view: function() {
      count++
      return m("div")
    }
  }
  m.module(root, module)

  mock.requestAnimationFrame.$resolve()

  return count === 3
})
```

I might be doing something wrong. Let me know

**Comment by lhorie** [comment] 2015-02-24 14:00
Hi @mindeavor 

Thanks for trying out the components branch! It's good to get some eyeballs on it before it gets released.

One issue I noticed in your snippet is that components need to have a virtual element as the return value.

**Comment by mindeavor** [comment] 2015-02-24 16:10
Ah, thanks, but that wasn't it. I updated the test to better match my app. Now it fails without breaking other tests:

```javascript
test(function() {
	// nested modules under keyed components should render
	mock.requestAnimationFrame.$resolve()

	var root = mock.document.createElement("div")
	var count = 0
	var App = {
		controller: function() {},
		view: function(ctrl) {
			return  m('.outer', [
				m('.inner', m.module(CommentList, { list: [1, 2, 3] }))
			])
		}
	}
	var CommentList = {
		controller: function() {},
		view: function(ctrl, props) {
			return m('.list', props.list.map(function(i) {
				return m('.comment', [
					m.module(Reply, {key: i})
				])
			}))
		}
	}
	var Reply = {
		controller: function() {},
		view: function() {
			count++
			return m(".reply")
		}
	}
	m.module(root, App)

	mock.requestAnimationFrame.$resolve()

	console.log("Count:", count)
	return count === 3
})
```

**Comment by lhorie** [comment] 2015-02-24 17:36
Thanks, I can reproduce the issue as well. I'll take a look into it

**Comment by mindeavor** [comment] 2015-02-24 20:39
Thanks! Components are looking great, and I can't wait to start using them for everything :)

**Comment by lhorie** [comment] 2015-02-24 22:54
The issue is that `m()` didn't account for a component as a second parameter. This is now fixed

**Closed by lhorie** 2015-02-24 22:54 UTC
Labels: bug

**Comment by mindeavor** [comment] 2015-02-24 23:42
:clap:
