### ISSUE TITLE
Mode to not clear out view until after route has loaded

### ISSUE THREAD

**Issue by andre-gh** [lhorie/mithril.js#789] opened 2015-09-03 19:15 UTC
Currently the router works such that it clears the contents out, then waits for computations to complete, then renders the new content.  The loading experience much better matches the browser (and feels less weird) if the content is not cleared out until after the computation wait has been completed. 

Is it possible to make Mithril leave the old view there until Mithril is ready to actually render the view out?

**Comment by andre-gh** [comment] 2015-09-03 19:55
To clarify, things are much smoother to the user if instead of the content of the page going away, the footer jumping up, the user is staring at empty space with a spinner appearing and a header and footer, then the content appearing:  It is much smoother to the user if the spinner appears, the old content stays, the new content appears, the spinner disappears.

How can I achieve this in Mithriljs.

**Comment by Bondifrench** [comment] 2015-09-03 20:38
Did you look at the wiki? You should check especially [recipes and snippets](https://github.com/lhorie/mithril.js/wiki/Recipes-and-Snippets).
Leo's blog is full of wisdom and even if he hasn't written for a while, I come back often to it as it contains many patterns that are very useful to make my code clearer and more functional.
For instance, Leo did write about how to show a loading icon [here](http://lhorie.github.io/mithril-blog/wait-for-it.html).
Cheers

**Comment by avesus** [comment] 2015-09-03 20:46
Put `m.redraw.strategy('diff')` into the both your page layout root component's `controller` methods.

**Comment by Zhouzi** [comment] 2015-09-04 11:29
I think @andre-gh suggests that Mithril should preload the next route before emptying the current one. So considering you're on the home page and click a link to navigate to another route, it should let the current page as is and load the next route to finally update the content. This way, the user is never staring at a blank screen.

The problem is, such behavior is actually rather complex. Mithril's router would have to handle preloading assets, data and so on. It might be out of scope but would be a great plugin to build!

**Comment by andre-gh** [comment] 2015-09-08 14:34
@avesus diff redrawing is not an option for me on route change

@Zhouzi Correct, this behavior is much more pleasant to a user using your site and feels much less slow or clunky.  It is of a huge benefit and I am pretty sure it should integrate into the startComputation endComputation system to decide when to clear out the view.

**Comment by barneycarroll** [comment] 2015-09-08 16:00
> diff redrawing is not an option for me on route change

@andre-gh why not? What you're describing is _exactly_ the behaviour of `diff` redraw mode; I'd recommend using the canonical API. If you're running into difficulties, we might be able to help with them…

> Mithril should preload the next route before emptying the current … such behavior is actually rather complex

@Zhouzi if you're talking about loading all the external resources (images, iframes, scripts etc) of a view before rendering it, you'd have to manage those resources yourself – you'd be right in describing that as complex!

**Comment by andre-gh** [comment] 2015-09-08 16:04
Diff redrawing is not an option because I have components on the page which after route change are taken over ownership by third party APIs and require a full redraw to re-init those components via the third party API.

I do not want diff redrawing, I still want the entire page redrawn, I just do not want Mithril to blow out the old page content until it is ready to actually place some new content in place (it waits for requests/computations to complete before doing so often) when changing routes.

**Comment by andre-gh** [comment] 2015-09-08 16:09
In other words, somewhere along the line this sequence of events occurs:

1) Route change
2) Remove existing content
3) Call controller
4) Redrawer wait for computations to complete
5) Draw new content

I would prefer this sequence of events:

1) Route change
2) Call controller
3) Redrawer wait for computations to complete
4) Remove existing content
5) Draw new content

I understand that diff redraw would basically accomplish this, but it does not fit my needs as many views render content which has the DOM handed off to some third party widget/polyfill/etc which alters aspects of the DOM and prevents proper redrawing with diff redrawing.

**Comment by barneycarroll** [comment] 2015-09-08 16:45
OK, _now_ I understand:

1) You can't use diff because the VDOM state is corrupted by config functions
2) There's a 'view-less' moment between changing routes and the async resolution of the second draw

So I can understand this as a legitimate bug. I think I've got a hack in mind though – it should be possible to extend your top level controllers to mitigate this effect. Gimme a while to think…

**Comment by andre-gh** [comment] 2015-09-08 17:25
Thank you, it sounds like you understand my problem.

**Comment by barneycarroll** [comment] 2015-09-08 18:06
The more I think about it, the more I think this is a serious bug. This behaviour is basically taking us back to pre-AJAX days, where you request a new resource and the page unloads before fetching a new one and rebuilding it. This is precisely the kind of stuff 20th century web app frameworks were developed to avoid.

I've written a (untested) function for transforming route components such that they avoid this problem: I doubt it's perfect (maybe the controller itself needs to `m.redraw.strategy( 'none' )` in order to avoid breaking `{ subtree }` behaviour: implementing this may not be ideal, but I'd appreciate insights if anybody has any: https://gist.github.com/barneycarroll/40141dd0af8734ddb173

I don't think the fix for this particular issue should be too difficult, but the root of the problem is something that Mithril 2.0 should seek to address: the behaviour of `m.redraw.strategy` and the use case and current implementation of `config` are built around the attitude that Mithril is a framework for building awesome web ~~applications~~ pages.

**Comment by pelonpelon** [comment] 2015-09-08 19:53
Many months ago I naively suggested that the final DOM should be "assembled" before rendering to the page. I know now that I misunderstood the `build` function. However, pre-assembly (before removing existing content) could be an option for route changes. It would resemble server-side rendering but use the browser's JS engine. But I'm concerned that what we are doing is circumventing modern browser optimizations.

I wonder if, upon a route change, we could *assemble* the new page in shadow-dom within the existing page using the current Mithril redraw system, allowing the browser to perform its optimizations as each element is appended, then "release" the content of the shadow-dom, replacing the old content with the new. I'm not even sure how this would be done. Can javascript move shadow-dom into the light-DOM?

**Comment by lhorie** [comment] 2016-12-01 07:48
This is difficult to fix in 0.2.x but rewrite does this

**Closed by lhorie** 2016-12-01 07:48 UTC
