### ISSUE TITLE
Propose: ng-animate like functionality in Mithril?

### ISSUE THREAD

**Issue by ludbek** [lhorie/mithril.js#791] opened 2015-09-11 04:24 UTC
Coming from Angular, the only thing I miss is the easiest and intuitive way one could animate elements being added, removed and moved. I know there are lots of ways one could achieve this in Mithril but all of them has to be hard coded into the component. I believe animations and transitions for changes in DOM are essential for pleasant UX and it has to be part of any modern web frameworks.

It would be great if Mithril adds appropriate classes to following DOM changes:
1. add new element
2. remove an element
3. move an element
4. data changes in an element e.g. could be used to flash an element when its content changes, useful for real time applications

**Comment by tinchoz49** [comment] 2015-09-11 12:18
Hi @ludbek i believe that the idea of mithril is keep the framework simple with a minimalistic API. But this kind of functionality can be implemented as an external module.
A few weeks ago i made something similar to ng-animate but instead of add classes in some changes on the DOM my library give us a callback function where you can do the animation as you want...using css3, velocityjs, etc
Is not documented ``yet```, but is easy to use and you have an example in the repository.

https://github.com/geut/mithril-transition

**Comment by lhorie** [comment] 2016-01-28 23:55
I may write a module for this for the rewrite. For the current v0.2.x stream, this is out of scope

**Closed by lhorie** 2016-01-28 23:55 UTC

**Comment by ludbek** [comment] 2016-02-01 11:51
@tinchoz49 @lhorie I have been working on [mithril-ui](). Its a work in progress. I could not help to show you guys the [animation module](https://github.com/ludbek/mithril-ui/blob/master/utils/animation.js) I wrote there. You can clone and test the animation.

Everything seems to work fine except for animating element being removed from DOM. I did manage to pull it off but the code is just too messy(not included in the module above). My approach was to hack around `.onunload`.

**Comment by barneycarroll** [comment] 2016-02-02 09:46
Hi @ludbek, this has been a desirable feature for a long time. I came up with my own implementation on the train this morning, [mithril.exitable](https://gist.github.com/barneycarroll/39c5d33d3a94e8ca5ad0).

Having explored and hacked around the limitations of Mithril components & virtual DOM statefulness for a while, I figured that (component controller instance : root element) was the most reliable contract, but I shied away from touching `onunload`, and instead opted for a new `exit` method where I could afford to take ownership of function signature without worrying about user expectations in that area.

I think I managed to keep code complexity to a minimum while providing a pretty simple and solid end use API. I'd be interested in your thoughts.

**Comment by ArthurClemens** [comment] 2016-02-02 12:45
An application needs to have transitions for showing and hiding. Just adding a class is not sufficient, because you need to know when the transition has ended. And some components need to do more than fade in or out.

In Polythene I've solved it like this:

* Component has functions [show](https://github.com/ArthurClemens/Polythene/blob/master/menu/menu.es6.js#L75) and `hide`.
* These functions call a [generic transition function](https://github.com/ArthurClemens/Polythene/blob/master/common/transition.es6.js#L84) with custom options (for instance the CSS 'show' class for that component)
* Transition options can be set in a theme too, for example to specify [beforeShow](https://github.com/ArthurClemens/Polythene/blob/master/notification/theme/snackbar/transitions.es6.js#L8) or `afterHide`
* Controller gets `transitioning` value
* When the transition is finished, the promise.then function is called to update the controller with the new state (and do some cleanup if needed)

**Comment by barneycarroll** [comment] 2016-02-02 17:52
@ArthurClemens interesting! So by your system you register an *intent* to modify the model, communicate that to the component, then make the actual change to the model that results in the component's destruction?

What does the application code for a full destruction sequence look like?

**Comment by ludbek** [comment] 2016-02-02 18:13
@barneycarroll Its a cleaver hack, loved it. I was having hard time animating nodes and components using single APIs. I can now see how it could be achieved. Thanx for the insight. Also I would love to incorporate your approach for handling exiting elements.

**Comment by barneycarroll** [comment] 2016-02-02 20:35
Glad you like the idea @ludbek, however I must admit I spent a couple of hours trying to get a functional demo and it doesn't quite work — I think the reason is that the last-minute subtree retain corrupts Mithril's internal snapshot and breaks subsequent diffs. I also seem to remember from previous exercises in this area that *this* is where you end up having to write a load of horrible code to second-guess and duplicate Mithril's internal model, and then hope you can trick it into behaving as if it wasn't performing all this logic we want to avoid. I'm afraid that this is one of those cases where the last 10% of the problem is 1000% of the code, and this might be a dead end after all :)

**Comment by ArthurClemens** [comment] 2016-02-02 22:07
@barneycarroll If you mean with "model" the view model, yes; at least the Polythene components only contain view states, if any. But of course you could have view states in a data model and use that to direct view components.

The behaviour of transitioning components varies a bit, dependent where they are drawn.

Dialog and Notification/Snackbar are shown in 1 container and generally only one at a time. They use helper component "Multiple" that maintains a queue (based on ids) and calls the next queued item (more useful for notifications than for dialogs). For instance `m.component(dialog)` creates a Multiple instance, and as long as it does not get any instructions, only a stub span is drawn. When an instance needs to be shown, Multiple gives it the property `show`. As long as the instance exists in the queue has this property, the instance component will be called. That is: during fade in transition; when it is shown; during fade out transition. 

So let's say that a dialog instance is already shown (with `dialog.show(options, id)`) and I want to remove it.

* A button click invokes `dialog.hide(id)`.
* Dialog is a Multiple, and it checks which instances need to be shown. Nothing has changed yet (hide transition is still about to start), so the instance is returned in its view function.
* Dialog instance view function checks `instanceData.hide && !ctrl.isTransitioning`. This is true, so call module function `hide`.
* Hide sets `ctrl.isTransitioning` to true, calls the `transition.hide` helper function with default options.
* `transition.hide` sets the transition duration and delay, removes the "show" class, and waits until the timeout.
* After the timeout, Multiple function "remove" is called with `dialog.remove(id)`. It is removed from the queue, so on the next redraw Multiple will no longer find this instance to show.
* `m.redraw` is called to clear the view and show the stub instead

Menu is not using Multiple because it does not use 1 stub container. Instead it is shown locally near the buttons where the menu should appear. I first made the mistake to handle menus like dialogs, but found out of course that they would never scroll with the rest of the page, so the menu would get disconnected.
Probably it is also better to have the menu in a local component where the view controller can store which menu row is selected and should be highlighted.

So a menu is instantiated with `m.component(menu, options)` where one of the options is `show` which will likely be a controller driven value. When the invoke button is clicked, that controller value will be set to true, and passed to the menu component. The menu will only be shown when the view function checks true for `opts.show && !ctrl.visible`.

Assuming this has happened, and the user clicked inside or outside of the menu to close it.

* The hide event is passed to a function with the component view.
* Module function `hide` is called
* Hide sets `ctrl.isTransitioning` to true, calls the `transition.hide` helper function with default options.
* Again `transition.hide` sets the transition duration and delay, removes the "show" class, and waits until the timeout.
* After the timeout, `ctrl.visible` is set to false, so the menu will no longer be shown at the next redraw.
* `m.redraw` is called to clear the view and show the stub instead

**Comment by barneycarroll** [comment] 2016-02-06 17:26
So I've managed to get [mithril.exitable.js](https://github.com/barneycarroll/mithril.exitable.js/) working. The toughest problem was that an exit animation trigger requires us to diff and patch the virtual DOM before swapping in a subtree retainer at the last moment. which corrupts Mithril's internal virtual DOM records, leading it to believe the patch has taken place. The solution is neater than I thought, though: by storing the view output of every component, we can do some [quick redraw API ninja work](https://github.com/barneycarroll/mithril.exitable.js/blob/master/src/exitable.es6.js#L78-L95) that patches Mithril's internal model back to its previous state before resuming normal lifecycle logic.

In the end, the ability to provide an arbitrary exit animation function to a component provides a tiny and simple API surface, requires far less convoluted application code, and offers maximum flexibility.

**Comment by isiahmeadows** [comment] 2016-02-07 03:29
@barneycarroll That solution looks cool IMHO. It basically shows how simple it is to make Mithril correct itself when it gets too eager in its redraws.

**Comment by barneycarroll** [comment] 2016-02-07 11:56
@isiahmeadows yeah, the crucial logic is [all here](https://github.com/barneycarroll/mithril.exitable.js/blob/master/src/exitable.es6.js#L69-L97), it's basically judicious use of memoization and the existing redraw API.

This was definitely more a product of thinking about how Mithril worked (away from the computer) rather than hacking away.

Knowing it's possible to do last minute subtree retainment and restore Mithril to a coherent internal state like this really extends the boundaries of what's possible with the 0.2 API. For instance, granular redraws seem within much closer reach now without any need to modify core.

**Comment by isiahmeadows** [comment] 2016-02-08 07:58
@barneycarroll :+1:
