### ISSUE TITLE
undefined vnode.state in node

### ISSUE THREAD

**Issue by magnusleo** [lhorie/mithril.js#1197] opened 2016-08-03 09:55 UTC
## Description:
`vnode.state` is not copied from `vnode.tag` when Mithril 1.0.0 "rewrite" is running in node.

### Steps to Reproduce:

Using this gist: https://gist.github.com/magnusleo/ac28737dd659db6465d9db47ab54495b
```
npm test
```

My test was run with node v5.9.1 on Mac OS X 10.11.5, installed using http://brew.sh/

### Expected:

The test runs flawlessly.

### Actual:

```javascript
component.js:15
                return m('li', {onclick: vnode.state.clickCurry(i)}, item); // Fails in node
                                                    ^

TypeError: Cannot read property 'clickCurry' of undefined
```

**Comment by pygy** [comment] 2016-08-03 11:10
The problem is not the copy, but the fact that `vnode.state` ends up being undefined.

Now that's eerie because I run the test suite on node all the time and [it covers that scenario](https://github.com/lhorie/mithril.js/blob/rewrite/render/tests/test-component.js#L642-L680).

Aaahh, ok, it's most likely a `mithril-query` bug. The Mithril copies the component to the state object `in `m.render` the first time it is rendered, just before calling `oninit`.

**Comment by magnusleo** [comment] 2016-08-03 11:19
Glad to hear Mithril has test coverage for these kind of things. I have drawn the attention of Mithril Query's authors, and we'll see where it leads.

**Comment by StephanHoyer** [comment] 2016-08-03 11:43
Will look in to this later...

**Comment by isiahmeadows** [comment] 2016-08-03 11:49
Closing as it's not a Mithril bug (per discussion in Gitter).

**Closed by isiahmeadows** 2016-08-03 11:49 UTC

**Comment by magnusleo** [comment] 2016-08-03 12:10
Reposted in the Mithril Query repo: https://github.com/StephanHoyer/mithril-query/issues/50
