### ISSUE TITLE
component parametrized with m.component() get its arguments list growing on every redraw

### ISSUE THREAD

**Issue by rielsi** [lhorie/mithril.js#638] opened 2015-05-29 06:06 UTC
```
var comp = {view: function(ctrl) {
    console.log(Array.prototype.slice.call(arguments));
}};
m.mount(document.body, m.component(comp, "test"));
setInterval(m.redraw, 1000);
```

Got in console:

```
[controller, "test", Array[1]]
[controller, "test", Array[1], Array[1]]
[controller, "test", Array[1], Array[1], Array[1]]
[controller, "test", Array[1], Array[1], Array[1], Array[1]]
...etc...
```

"Pure" component aren't affected, it only happens if wrapped with m.component().

**Comment by venning** [comment] 2015-06-11 22:54
I'm looking into this, but don't have an answer yet.

On the surface, the problem is [here (line 561)](https://github.com/lhorie/mithril.js/blob/next/mithril.js#L561):

```javascript
function parameterize(component, args) {
    var controller = function() {
        return (component.controller || noop).apply(this, args) || this
    }
    var view = function(ctrl) {
        if (arguments.length > 1) args = args.concat([].slice.call(arguments, 1))
        return component.view.apply(component, args ? [ctrl].concat(args) : [ctrl])
    }
    view.$original = component.view
    var output = {controller: controller, view: view}
    if (args[0] && args[0].key != null) output.attrs = {key: args[0].key}
    return output
}
```

Each call to `view` internally is supplied with `[ {} ]` as an additional argument, at least in your example.  The problem is that `parameterize` keeps appending the additional supplied arguments onto `args` before applying them to the view function, so each run of `view` gets all of the previous runs' arguments as well.

**Options:**
   - This might actually be expected behavior, but I can't imagine any view function actually parsing for all those ever-increasing arguments.
   - Possibly, there is some buggy behavior supplying that `[ {} ]`.
   - Only the current execution of `view` should have the supplied argument appended.

The third option seems most likely to me, which would look something like:

```javascript
function parameterize(component, args) {
    var controller = function() {
        return (component.controller || noop).apply(this, args) || this
    }
    var view = function(ctrl) {
        var currentArgs = arguments.length > 1 ? args.concat([].slice.call(arguments, 1)) : args
        return component.view.apply(component, currentArgs ? [ctrl].concat(currentArgs) : [ctrl])
    }
    view.$original = component.view
    var output = {controller: controller, view: view}
    if (args[0] && args[0].key != null) output.attrs = {key: args[0].key}
    return output
}
```

**Comment by rielsi** [comment] 2015-06-12 05:27
Thank you. It certainly looks buggy and "leaky" to me. I settle down on stuffing all parameters into the second argument (which "is meant to be used as an attribute map and should be an object"), so I can deliver arguments on to arbitrary level of a deeply nested components tree. It's also more conscious to have those arguments explicitly named.

**Comment by pelonpelon** [comment] 2015-06-12 22:12
It looks like your solution puts a stop to the recursive calls to **view** (internally).
http://jsbin.com/noxecu/1/edit?js,console ( w/ modified mithril.js = http://output.jsbin.com/casote/9.js )

Make a pull request and see what Leo thinks.

But we're still left with a circular controller.
I don't know. Is that a problem?

**Comment by venning** [comment] 2015-06-15 21:55
@pelonpelon, what do you mean by "circular controller"?

**Comment by mrtracy** [comment] 2015-06-16 01:03
I believe that `m.component` was designed to be always called inside of another `view()` function.  Each time that containing `view()` function is called, a completely new "parameterized" object would be instantiated; thus, the expectation would be for each "parameterized" object to have its view method called only one time.

However, when passed to `m.mount()`, the parameterized object is now having it's view method called repeatedly; this was perhaps an unexpected usage of m.component, thus the bug.

**Comment by venning** [comment] 2015-06-16 22:36
Thanks, @mrtracy.  If that's the case, then that explains a lot.  However, I can foresee non-contrived use cases for *wanting* to parameterize a component and then mount it, so maybe the documentation should specify not doing that.  There are ways to make parameterized components break on mount to prevent this usage, notably not creating a `{ view: ..., controller: ... }` object inside of `parameterize`.

Either way, the functionality shouldn't be constantly growing the argument array it applies to `view`.

---

Okay, so is there an earlier discussion (maybe in a GitHub issue) that explains a little more of how Mithril approaches components?  The implementation and documentation seem not quite done yet and I don't know how to approach helping.

To be clear, I am extremely grateful that Mithril adopted components, but I'm just not sure if the design or implementation is still in flux.

**Comment by tivac** [comment] 2015-06-16 23:56
@venning http://mithril.js.org/mithril.component.html

Note that the signature for [`m.mount`](http://mithril.js.org/mithril.mount.html) calls out that it accepts a component, not a parameterized component (the result of calling `m.component()`). It seems like this is more of a documentation/nomenclature issue than a code one.

**Comment by venning** [comment] 2015-06-17 00:20
@tivac, actually, I think that proves my point.  On the same page, it states that
> calling `m.component(MyComponent, {foo: "bar"})` will return a component that behaves exactly the same as `MyComponent`, but `{foo: "bar"}` will be bound as an argument to both the `controller` and `view` functions.

The documentation seems to indicate that there is no practical difference between a component and a parameterized component, which makes sense in terms of how I would use them.  I don't want to be geared up for components and then decide that something needs to be stuffed in to their parameters and then be forced to rewrite my codebase to handle such a small semantic difference.

On a philosophical note, subtle distinctions between seemingly identical concepts is exactly what I dislike about Angular in practice.  Based on his writing, I would imagine @lhorie would also like to reduce the "cognitive load" of having to distinguish from small things like whether or not a component is or isn't parameterized.

**Comment by isiahmeadows** [comment] 2016-11-23 07:54
Closing, since it's fixed now.

**Closed by isiahmeadows** 2016-11-23 07:54 UTC
