### ISSUE TITLE
Bug(probably) with prerendered templates

### ISSUE THREAD

**Issue by Ashot-KR** [lhorie/mithril.js#1006] opened 2016-03-30 09:31 UTC
https://jsfiddle.net/pka3at9y/ here is fiddle.
There is a view which renders some div elements from an array and one "static" div right after them.
Click on "add" button pushes new element into array and rerenders view with new elements, and "static" div element duplicates on each click.
If `attrs`(even empty object) to "static" element or remove `key` attribute from array elements fixes issue.

Rendering using `m()` function does not behaves like that.

P.S. Sorry for my english :)

**Comment by barneycarroll** [comment] 2016-03-30 09:40
There are occasionally strange edge-case behaviours relating to keys, so this might be worth further investigation, but I would caution that `{ tag : String, children : String }` is an invalid virtual DOM node. When arguments are passed to `m()`, Mithril performs some logic to guarantee valid virtual DOM output, but a properly formed virtual DOM node must be either a string (in the case of a text node) or an object conforming to: `{ tag : String, attrs : Object, children : Array }`.

**Comment by Ashot-KR** [comment] 2016-03-30 10:09
@barneycarroll in real life i'd never write such code :) i found this behavior while exploring and experimenting with mithril. I was using [msx](https://github.com/insin/msx), and it generates `{ tag : String, children : String }` when there is no any attributes on tag.
May be this is msx issue, but there is still any chance that someone will code something like `{ tag : String, children : String }` manually.

**Comment by isiahmeadows** [comment] 2016-03-30 19:01
@Ashot-KR @barneycarroll I believe this is very related to #912 and #956, possibly a partial dupe of both.

**Comment by Ashot-KR** [comment] 2016-03-30 22:14
Looks like i found a problem. #1007
@isiahmeadows i think #912 is same issue, but it needs more complex workarounds, because we can't just make `attrs.attrs == attrs.attrs || {}`(as i've done for objects in my PR) if `attrs` is `String`.

**Comment by isiahmeadows** [comment] 2016-05-07 20:55
Closing this, since the PR in #1007 was rejected.

**Closed** 2016-05-07 20:54 UTC
