### ISSUE TITLE
Typescript header thinks controller is mandatory in Component 

### ISSUE THREAD

**Issue by baturinsky** [lhorie/mithril.js#1349] opened 2016-10-08 05:47 UTC
### Description:

Typescript header thinks controller property is mandatory in Component 

### Steps to Reproduce:

This (or any other component with only view) is not compiling as TypeScript
```
var pageMain = {
  view: (w) => {
    return mPage(m("div",  m("span", "Some text") ) )
  }
}
```

### Suggested solution

There should be a question mark after "controller" property ofComponent in mithril.d.ts, like this

```
	/**
	* This represents a Mithril component.
	*
	* @see m
	* @see m.component
	*/
	interface Component<T extends Controller> {
		/**
		* The component's controller.
		*
		* @see m.component
		*/
		controller?: ControllerFunction<T> | ControllerConstructor<T>;

		/**
		* Creates a view out of virtual elements.
		*
		* @see m.component
		*/
		view(ctrl?: T, ...args: any[]): VirtualElement;
	}
```

**Comment by isiahmeadows** [comment] 2016-10-24 16:11
Closing as duplicate of #1336.

**Closed by isiahmeadows** 2016-10-24 16:11 UTC
