### ISSUE TITLE
Bad children orders with m()

### ISSUE THREAD

**Issue by daiyam** [lhorie/mithril.js#1040] opened 2016-05-07 10:01 UTC
Hi,

I was working on [js-framework-benchmark](https://github.com/daiyam/js-framework-benchmark/tree/mithril) when Stefan (the original author of the benchmark) pointed to me a bug in Mithril.
When we add a row to the list, the should be before-last is displayed as the last item.

I've isolated the bug with some fiddles:
[working correctly](https://jsfiddle.net/8a4e01xw/)
[same but with m() and the bug](https://jsfiddle.net/adceg2ee/)

Thx
Baptiste

**Comment by isiahmeadows** [comment] 2016-05-07 21:07
@daiyam Try adding `attrs: {}`. The API assumes the attributes already exist. It's a bug in the benchmark itself, from a small breaking change to the API here (it had a very low impact everywhere else mod the MSX issue).

Closing, since as it stands, it's a duplicate of #1006, where the related PR, #1007, was rejected. It's more of an implementation detail that leaked out into the public API by necessity. Internally, `attrs` is assumed to exist to both simplify the implementation and make `m()` easier for engines to optimize by returning a single static structure, and those assumptions aren't likely to change soon.

The other issue, #1006, stemmed from an issue with the MSX compiler (read: Mithril + JSX), where it omitted that property previously, but was affected by the breaking change (I forgot to announce it).

**Closed by isiahmeadows** 2016-05-07 21:07 UTC

**Comment by daiyam** [comment] 2016-05-07 21:51
Hi Isiah,

When you know the bug, it's easy to fix. I just had to replace `null` with `{}` or with msx, add `class=''`.
But it's a bug, it should be fixed. Or at least, listed on the known issues.

**Comment by isiahmeadows** [comment] 2016-05-08 01:59
@daiyam It is an easy fix, but it's not likely to get fixed, as it's intentional behavior.
